packages:
  - apps/*
  - packages/*
  - templates/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.5'
  - '@better-auth/drizzle-adapter@1.7.5'
  - '@better-auth/kysely-adapter@1.7.5'
  - '@better-auth/memory-adapter@1.7.5'
  - '@better-auth/mongo-adapter@1.7.5'
  - '@better-auth/prisma-adapter@1.7.5'
  - '@better-auth/telemetry@1.7.5'
  - better-auth@1.7.5
