import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
const ROOT=new URL('./',import.meta.url).pathname;
const env=Object.fromEntries(readFileSync(process.env.HOMI_TEST_CREDENTIALS ?? '/tmp/homi-shopping-browser/bootstrap.env','utf8').trim().split('\n').map(s=>{const i=s.indexOf('=');return [s.slice(0,i),s.slice(i+1)];}));
const run=Date.now().toString().slice(-7),base=process.env.HOMI_TEST_URL ?? 'http://localhost:3300';
if(new URL(base).hostname!=='localhost')throw new Error('Acceptance fixtures require the isolated localhost test stack');
const contexts=[],errors=[],results=[];
const pass=s=>{results.push(s);console.log('PASS',s);};
async function launch(label,offline=false){const dir='/tmp/homi-shopping-browser/profile-'+label+'-'+run;const ctx=await chromium.launchPersistentContext(dir,{headless:true,viewport:{width:390,height:844},offline});contexts.push(ctx);const p=ctx.pages()[0]??await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));return {ctx,p,dir};}
async function login(d,email=env.HOMI_BOOTSTRAP_EMAIL){await d.p.goto(base);await d.p.getByLabel('Email',{exact:true}).fill(email);await d.p.getByLabel('Password',{exact:true}).fill(env.HOMI_BOOTSTRAP_PASSWORD);await d.p.getByRole('button',{name:'Sign in',exact:true}).click();await d.p.getByRole('button',{name:/Open list$/}).waitFor({timeout:20000});}
async function open(d){await d.p.getByRole('button',{name:/Open list$/}).click();await d.p.getByRole('heading',{name:'Shopping List',exact:true}).waitFor();}
async function rows(d,store){return d.p.evaluate(async store=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('homi-client');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});return await new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>{db.close();res(r.result)};r.onerror=()=>rej(r.error);});},store);}
async function identity(d){return JSON.parse((await rows(d,'meta')).find(r=>r.key==='activeOfflineContext').value);}
async function api(d,path,body){const id=await identity(d);return d.p.evaluate(async({path,body,id})=>{const r=await fetch('/api/v1/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Homi-Household-ID':id.householdId,'X-Homi-Client-ID':id.clientId},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};},{path,body,id});}
async function poll(fn,message){let last;for(let i=0;i<45;i++){try{last=await fn();if(last)return;}catch(e){last=e.message;}await new Promise(r=>setTimeout(r,1000));}throw new Error(message+': '+JSON.stringify(last));}
async function add(d,name){await d.p.getByRole('textbox',{name:'Add an item',exact:true}).fill(name);await d.p.getByRole('button',{name:'Add',exact:true}).click();await d.p.getByRole('checkbox',{name,exact:true}).waitFor();}
async function edit(d,name,qty){await d.p.getByRole('button',{name:'Edit '+name,exact:true}).click();await d.p.getByLabel('Quantity',{exact:true}).fill(qty);await d.p.getByRole('button',{name:'Save item',exact:true}).click();}
async function restart(d){await d.ctx.close();const ctx=await chromium.launchPersistentContext(d.dir,{headless:true,viewport:{width:390,height:844},offline:true});contexts.push(ctx);d.ctx=ctx;d.p=ctx.pages()[0]??await ctx.newPage();d.p.on('pageerror',e=>errors.push(e.message));await d.p.goto(base);await d.p.getByRole('button',{name:/Open list$/}).waitFor({timeout:20000});await open(d);}
try{
const a=await launch('a'),b=await launch('b'),c=await launch('c');
await login(a);await login(b);await login(c,'shopping-second@example.invalid');await open(a);await open(b);await open(c);
const ia=await identity(a),ib=await identity(b),ic=await identity(c);assert.equal(ia.authSubject,ib.authSubject);assert.notEqual(ia.clientId,ib.clientId);assert.notEqual(ia.authSubject,ic.authSubject);assert.equal(ia.householdId,ic.householdId);pass('two registered devices and a distinct authorized household user');
const name='Milk '+run;await add(a,name);await poll(async()=> (await api(a,'modules/shopping/items')).body.data.some(i=>i.name===name),'online create');
await poll(async()=>await b.p.getByRole('checkbox',{name,exact:true}).count(),'second device');await poll(async()=>await c.p.getByRole('checkbox',{name,exact:true}).count(),'second user');pass('online create propagates automatically to second device and second user');
await a.p.evaluate(()=>navigator.serviceWorker.ready);await restart(a);pass('full browser/PWA restart offline loads Shopping assets and data');
const bread='Bread '+run;await add(a,bread);await edit(a,bread,'2');await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).click();await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).waitFor({state:'detached'});await a.p.getByRole('button',{name:/^Checked \(/}).click();assert.equal(await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).isChecked(),true);await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).click();await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).waitFor({state:'detached'});await a.p.getByRole('button',{name:'To buy',exact:true}).click();
await edit(a,name,'3');const removed='Delete '+run;await add(a,removed);await a.p.getByRole('button',{name:'Edit '+removed,exact:true}).click();await a.p.getByRole('button',{name:'Remove item',exact:true}).click();await a.p.getByRole('checkbox',{name:removed,exact:true}).waitFor({state:'detached'});assert.equal(await a.p.getByRole('checkbox',{name:removed,exact:true}).count(),0);
await restart(a);await a.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).waitFor();await a.p.getByRole('checkbox',{name:name+' · 3',exact:true}).waitFor();assert.equal(await a.p.getByRole('checkbox',{name:removed,exact:true}).count(),0);pass('offline create/edit/check/uncheck/delete survive another full restart');
await a.ctx.setOffline(false);await poll(async()=>!(await rows(a,'mutations')).some(m=>m.moduleKey==='shopping'&&['queued','sending'].includes(m.status)),'automatic reconnect drain');const pending=await rows(a,'mutations');assert.deepEqual(pending.filter(m=>m.moduleKey==='shopping'&&['conflict','rejected'].includes(m.status)),[]);
await poll(async()=>await b.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).count(),'device reconnect propagation');await poll(async()=>await c.p.getByRole('checkbox',{name:bread+' · 2',exact:true}).count(),'member reconnect propagation');pass('reconnect applies every queued edit automatically without self-conflicts');
await a.ctx.setOffline(true);await edit(a,name,'4');await edit(b,name,'5');await poll(async()=> (await api(b,'modules/shopping/items')).body.data.find(i=>i.name===name)?.quantity==='5','remote edit');await a.ctx.setOffline(false);await a.p.getByText('Someone changed this item before your change arrived.',{exact:false}).waitFor({timeout:30000});await a.p.getByRole('button',{name:'Review item',exact:true}).click();await a.p.getByRole('button',{name:'Cancel',exact:true}).click();await a.p.getByRole('button',{name:'Review item',exact:true}).waitFor();pass('stale revision is reviewable and cancelling review preserves conflict');await a.p.getByRole('button',{name:'Keep shared version',exact:true}).click();await a.p.getByRole('checkbox',{name:name+' · 5',exact:true}).waitFor();
for(const width of [390,768,1440]){await a.p.setViewportSize({width,height:900});assert.equal(await a.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await a.p.evaluate(()=>scrollTo(0,0));await a.p.screenshot({path:ROOT+'/shopping-'+width+'.png',fullPage:true});}pass('phone/tablet/desktop layout has no horizontal overflow');
assert.deepEqual(errors,[]);pass('no JavaScript page errors');
writeFileSync(ROOT+'/browser-acceptance.json',JSON.stringify({date:new Date().toISOString(),run,results},null,2));
}catch(e){console.error(e);writeFileSync(ROOT+'/browser-failure.txt',String(e.stack));for(const [i,ctx]of contexts.entries()){try{const p=ctx.pages()[0];if(p){console.log('PAGE',i,(await p.locator('body').innerText()).slice(0,3000));await p.screenshot({path:ROOT+'/failure-'+i+'.png'});}}catch{}}process.exitCode=1;}finally{for(const ctx of contexts)await ctx.close().catch(()=>{});}
